### ISSUE TITLE
Loop through history table - only works if a 1th entry exists

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/community-scripts#77]
eg:
https://github.com/zaproxy/community-scripts/blob/8a9da8a43df28a7becf033298fc3367f01a6a2f3/standalone/Loop%20through%20history%20table.js#L14

Nothing gets displayed if history record no.1 is removed. Further the 'loop' only works if the IDs are sequential.

There is a way to get the last history id:
https://github.com/zaproxy/community-scripts/blob/8a9da8a43df28a7becf033298fc3367f01a6a2f3/standalone/historySourceTagger.js#L19

But there does not appear to be an equivalent for the first. Even so, that wouldn't solve the issue of non-contiguous ranges.

**This isn't a show stopper but might be worth documenting in the script.**

**Comment by thc202** [comment]
The script could ignore missing IDs and loop until the last history ID, or, obtain the IDs of the messages from the History table (DB).
