### ISSUE TITLE
Break example

### ISSUE THREAD

**Issue by Naramsim** [zaproxy/community-scripts#81]
Hi, it would be useful to add an example on how to use breaks (breakpoints).

https://github.com/zaproxy/zaproxy/wiki/ApiGen_break

**Comment by psiinon** [comment]
Thats non tricky - you essentially need to provide your own interface, either graphical or command line.
It can definitely be done, but possibly not in a simple example.
Do you have a need to do this? If so what are you trying to do and we might be able to offer more advice...

**Comment by Naramsim** [comment]
I basically need to stop the traffic when I intercept a request, in order to clear the cookies/relaunch the browser to perform other tasks (programmatically).

So an example could be: Visit login page, submit login, intercept login request, stop traffic, restart browser and clear cookies, resend login request without a parameter (ie: Referer), check response, end
